evaluacion_6.1/app1/urls.py
from django.urls import path
from . import views

app_name="app1"

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('home/', views.home),
    path('exams/', views.exams),
    path('meds/', views.meds),
    path('cal/', views.cal, name='cal'),
    path('lista/', views.ListaPaciente.as_view(), name='lista'),
    path('crear/', views.CrearPaciente.as_view(), name='crear'),
    path('<int:pk>/editar', views.EditarPaciente.as_view(), name='editar'),
    path('<int:pk>/eliminar', views.EliminarPaciente.as_view(), name='eliminar'),
    path('examenes/', views.ExamenesView.as_view(), name='examenes'),
    #path('agregar_examenh/', views.AgregarExamenh.as_view(), name='agregar_examen'),
    #path('<int:pk>/eliminar_examenh', views.EliminarExamenh.as_view(), name='eliminar_examen'),
    #path('crear_examenpl/', views.AgregarExamenpl.as_view(), name='agregar_examen'),
    #path('<int:pk>/eliminar_examenh', views.EliminarExamenpl.as_view(), name='eliminar_examen'),
    #path('crear_examenpb/', views.AgregarExamenpb.as_view(), name='agregar_examen'),
    #path('<int:pk>/eliminar_examenpb', views.EliminarExamenpb.as_view(), name='eliminar_examen'),
    path('lista_medicamentos/', views.ListaMedicamentos.as_view(), name='lista_medicamentos'),
    path('agregar_medicamento/', views.AgregarMedicamento.as_view(), name='agregar_medicamento'),
    path('<int:pk>/editar_medicamento', views.EditarMedicamento.as_view(), name='editar_medicamento'),    
    path('<int:pk>/eliminar_medicamento', views.EliminarMedicamento.as_view(), name='eliminar_medicamento'),
]

evaluacion_6.1/meds2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
]

evaluacion_6.1/app1/models.py
from django.db import models

# Create your models here.

class Paciente(models.Model):
    run = models.CharField(max_length=8, primary_key=True)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField()
    edad = models.IntegerField()
    direccion = models.CharField(max_length=50)
    email = models.CharField(max_length=100, null=True)
    telefono = models.IntegerField()
    patologias = models.CharField(max_length=2000)

class ExamenHemograma(models.Model):
    fecha = models.DateField()
    hematocrito = models.DecimalField(max_digits=5, decimal_places=2)
    hemoglobina = models.DecimalField(max_digits=5, decimal_places=2)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)

class ExamenPerfill(models.Model):
    fecha = models.DateField()
    colesterol_total = models.DecimalField(max_digits=5, decimal_places=2, blank = True)
    trigliceridos = models.DecimalField(max_digits=5, decimal_places=2, blank = True)    
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)

class ExamenPerfilb(models.Model):
    fecha = models.DateField()
    glucosa = models.DecimalField(max_digits=5, decimal_places=2, blank = True)
    bilirrubina_total = models.DecimalField(max_digits=5, decimal_places=2, blank = True)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)

class Medicamento(models.Model):
    codigo = models.CharField(max_length=8, primary_key=True)
    fecha_indicacion = models.DateField()
    nombre = models.CharField(max_length=50)
    dosis = models.CharField(max_length=50)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)

evaluacion_6.1/app1/views.py
from django.shortcuts import render
from django.views.generic import ListView, View
from django.views import generic
from .models import Paciente, ExamenHemograma, ExamenPerfill, ExamenPerfilb, Medicamento
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy 


# Create your views here.

def inicio(request):
    return render(request, 'app1/index.html')

def home(request):
    return render(request, 'app1/main.html') 

def register(request):
    return render(request, 'app1/registro.html')  

def exams(request):
    return render(request, 'app1/examenes.html') 

def meds(request):
    return render(request, 'app1/medicamento.html')

def cal(request):
    return render( request, 'app1/calendario.html')



class Inicio(generic.TemplateView):
    template_name = 'app1/index.html'


class ListaPaciente(ListView):
    model=Paciente
    template_name = 'app1/lista_paciente.html'
    context_object_name = 'paciente'


class CrearPaciente(CreateView):
    model=Paciente
    template_name = 'app1/crear_paciente.html'
    fields='__all__'
    success_url= reverse_lazy('app1:lista')


class EditarPaciente(UpdateView):
    model=Paciente
    template_name = 'app1/editar_paciente.html'
    fields='__all__'
    success_url=reverse_lazy('app1:lista')


class EliminarPaciente(DeleteView):
    model=Paciente
    template_name = 'app1/eliminar_paciente.html'
    fields='__all__'
    success_url=reverse_lazy('app1:lista')
    context_object_name = 'paciente'


class ExamenesView(View):
    template_name = 'app1/examenes.html'
    success_url = 'app1:examenes'

class ListaExamenesH(ListView):
    model=ExamenHemograma
    template_name = 'app1/examenes.html'
    context_object_name = 'examen'

class AgregarExamenh(CreateView):
    model=ExamenHemograma
    template_name = 'app1/agregar_examen.html'
    fields='__all__'
    success_url= reverse_lazy('app1:examenes')

class EliminarExamenh(DeleteView):
    model=ExamenHemograma
    template_name = 'app1/eliminar_examen.html'
    fields='__all__'
    success_url=reverse_lazy('app1:examenes')
    context_object_name = 'examen'

class ListaExamenespl(ListView):
    model=ExamenPerfill
    template_name = 'app1/examenes.html'
    context_object_name = 'examen'

class AgregarExamenpl(CreateView):
    model=ExamenPerfill
    template_name = 'app1/agregar_examen.html'
    fields='__all__'
    success_url= reverse_lazy('app1:examenes')

class EliminarExamenpl(DeleteView):
    model=ExamenPerfill
    template_name = 'app1/eliminar_examen.html'
    fields='__all__'
    success_url=reverse_lazy('app1:examenes')
    context_object_name = 'examen'

class ListaExamenespb(ListView):
    model=ExamenPerfilb
    template_name = 'app1/examenes.html'
    context_object_name = 'examen'

class AgregarExamenpb(CreateView):
    model=ExamenPerfilb
    template_name = 'app1/agregar_examen.html'
    fields='__all__'
    success_url= reverse_lazy('app1:examenes')

class EliminarExamenpb(DeleteView):
    model=ExamenPerfilb
    template_name = 'app1/eliminar_examen.html'
    fields='__all__'
    success_url=reverse_lazy('app1:examenes')
    context_object_name = 'examen'


class ListaMedicamentos(ListView):
    model=Medicamento
    template_name = 'app1/lista_medicamentos.html'
    context_object_name = 'medicamento'

class AgregarMedicamento(CreateView):
    model=Medicamento
    template_name = 'app1/agregar_medicamento.html'
    fields='__all__'
    success_url= reverse_lazy('app1:lista_medicamentos')

class EditarMedicamento(UpdateView):
    model=Medicamento
    template_name = 'app1/editar_medicamento.html'
    fields='__all__'
    success_url=reverse_lazy('app1:lista_medicamentos')


class EliminarMedicamento(DeleteView):
    model=Medicamento
    template_name = 'app1/eliminar_medicamento.html'
    fields='__all__'
    success_url=reverse_lazy('app1:lista_medicamentos')
    context_object_name = 'medicamento'

evaluacion_6.1/app1/templates/app1/agregar_examen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        <table border="1">
            {{form.as_table}}
        </table>
        <input type="submit" value="Guardar">
        <a href="{% url 'app1:lista' %}"><button type="button">Cancelar</button></a>
    </form>

</body>
</html>

evaluacion_6.1/app1/templates/app1/agregar_medicamento.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        <table border="1">
            {{form.as_table}}
        </table>
        <input type="submit" value="Guardar">
        <a href="{% url 'app1:lista_medicamentos' %}"><button type="button">Cancelar</button></a>
    </form>

</body>
</html>

evaluacion_6.1/app1/templates/app1/editar_paciente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        <table border="1">
            {{form.as_table}}
        </table>
        <input type="submit" value="Guardar">
        <a href="{% url 'app1:lista' %}"><button type="button">Cancelar</button></a>
    </form>
</body>
</html>

evaluacion_6.1/app1/templates/app1/eliminar_examen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        <table border="1">
            {{form.as_table}}
        </table>
        <input type="submit" value="Guardar">
        <a href="{% url 'app1:lista' %}"><button type="button">Cancelar</button></a>
    </form>

</body>
</html>

evaluacion_6.1/app1/templates/app1/eliminar_medicamento.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST"> 
        {% csrf_token %} 
        Está seguro de eliminar el medicamento =  {{medicamento.run}}?
        <input type="submit" value="Sí" /> 
        <a href="{% url 'app1:lista_medicamentos' %}">Cancelar</a>
</body>
</html>

evaluacion_6.1/app1/templates/app1/eliminar_paciente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST"> 
        {% csrf_token %} 
        Está seguro de eliminar el paciente =  {{paciente.run}}?
        <input type="submit" value="Sí" /> 
        <a href="{% url 'app1:lista' %}">Cancelar</a>
</body>
</html>

evaluacion_6.1/app1/templates/app1/index.html
{% load static %}

<!doctype html>
<html lang="es">

<head>
  <title>SINARS</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Loading Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="css/style.css">
</head>

<body>
  <!-- Navigation Bar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">SINARS</a>

    <!-- Navigation Bar Hamburger-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false"
      aria-controls="navigation" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- End Navigation Bar Hamburger -->
    <!-- Navigation Links -->
    <div class="collapse navbar-collapse" id="navigation">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">

        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
            aria-expanded="false">
            Login <span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            <form class="px-4 py-3">
              <div class="form-group">
                <label >Email</label>
                <input type="email" class="form-control" id="login-user" placeholder="email@xxx.com">
              </div>
              <div class="form-group">
                <label>Contraseña</label>
                <input type="password" class="form-control" id="login-pass" placeholder="Contraseña">
              </div>
              <div class="form-group">
                <div class="form-check">
                  <input type="checkbox" class="form-check-input" id="dropdownCheck">
                  <label class="form-check-label" for="dropdownCheck">
                    Recordar Datos
                  </label>
                </div>
              </div>
              <button type="button" class="btn btn-primary" onclick="login()">Ingresar</button>
            </form>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="registro.html">No está registrado? Regístrese aquí</a>
            <a class="dropdown-item" href="#">Olvidó su contraseña?</a>
          </div>
          <div class="dropdown-menu dropdown-menu-right">
          </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Buscar" aria-label="Buscar">
        <button class="btn btn-outline-success border-dark 
                    font-weight-bold text-white my-2 my-sm-0" type="submit">Buscar</button>
      </form>
    </div>
    <!-- Navigation Links -->
  </nav>
  <!-- End Navigation Bar -->

  <!-- Section: Principal -->
  <div class="jumbotron">
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'img/coronavirus2.jpg' %}" class="d-block w-100" alt="50">
          <div class="carousel-caption d-none d-md-block">
            <h1>SINARS</h1>
            <p class="h2">Primer sistema de registro nacional de datos de salud de Chile</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/nurse.jpg' %}" class="d-block w-100" alt="50">
          <div class="carousel-caption d-none d-md-block">
            <h1>SINARS</h1>
            <p class="h2">Primer sistema de registro nacional de datos de salud de Chile</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/dpctpriiiiiiiiiiiiiiiiiiikkkkkkkkkkkkkj8.jpg' %}" class="d-block w-100" alt="50">
          <div class="carousel-caption d-none d-md-block">
            <h1>SINARS</h1>
            <p class="h2">Primer sistema de registro nacional de datos de salud de Chile</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  <!-- End Section: Principal -->

  <!-- Section: Competencias -->
  <div class="container-fluid noticias">

    <div class="row">
      <h2>Noticias de Interés</h2>
    </div>
    <div class="row">
      <div class="col-md-6 col-lg-3">
        <div class="card">
          <h2 class="card-header">Curso Cuidado Integral</h2>
          <div class="card-body">
            <h3 class="card-title">Inicio: 24 de Noviembre</h3>
            <p class="card-text">Curso semipresencial de 120 horas de duración que busca contribuir al fortalecimiento y
              puesta en práctica de los conocimientos, actitudes y habilidades relacionadas con el abordaje y manejo
              integral de los usuarios adultos mayores que se atienden en atención primaria.</p>
            <a href="#!" class="btn btn-dark">Ver mas</a>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="card">
          <h2 class="card-header">Agenda País: Mes del Adulto Mayor</h2>
          <div class="card-body">
            <h3 class="card-title">Mes del Adulto Mayor</h3>
            <p class="card-text">Talleres, apoyo económico y programas de salud buscan potenciar el envejecimiento
              positivo.</p>
            <a href="#!" class="btn btn-dark">Ver mas</a>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="card">
          <h2 class="card-header">Tendencias: La Risoterapia</h2>
          <div class="card-body">
            <h3 class="card-title">El mágico poder tonificante de la risa</h3>
            <p class="card-text">La risoterapia o terapia de risas aporta grandes beneficios en la salud física y
              emocional del adulto mayor, especialmente para afrontar los momentos de #soledad y depresión tan comunes
              en la vejez.</p>
            <a href="#!" class="btn btn-dark">Ver mas</a>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="card">
          <h2 class="card-header">Coronavirus en el Mundo</h2>
          <div class="card-body">
            <h3 class="card-title">¿Puede el covid-19 convertirse en un virus endémico?</h3>
            <p class="card-text">Todavía se desconoce mucho sobre la covid-19 y el virus que la causa, el SARS-Cov-2,
              pero como han mostrado otras infecciones en el pasado, es muy probable que este coronavirus continúe
              transmitiéndose, incluso si contamos con una vacuna.</p>
            <a href="#!" class="btn btn-dark">Ver mas</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Section: Competencias -->

  <!-- Section: Enlaces -->
  <div class="container-fluid bg-dark text-center">
    <div class="row">
      <h3>Enlaces de Interés</h3>
    </div>
    <div class="row">
      <div class="col-md-4">
          <a href="https://www.hospitaldigital.gob.cl/"> <img class="img-fluid img-logo"  src="{% static 'img/logo-hospital-digital.png' %}" alt="..."> </a>
      </div>
      <div class="col-md-4">
        <a href="https://samu.cl/"> <img class="img-fluid img-logo"  src="{% static 'img/Logo-SAMU-Metropolitano.png' %}" alt="..." > </a>
      </div>
      <div class="col-md-4">
        <a href="https://www.doctoralia.cl/"> <img class="img-fluid img-logo"  src="{% static 'img/logo-doctoralia.png' %}" alt="..." > </a>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
      <a href="https://www.fonasa.cl/sites/fonasa/inicio"> <img class="img-fluid img-logo"  src="{% static 'img/fonasa.png' %}" alt="..." > </a>
      </div>
      <div class="col-md-6">
       <a href="http://www.isapre.cl/home"> <img class="img-fluid img-logo"  src="{% static 'img/logoisapre.png' %}" alt="..." > </a>
      </div>
    </div>
  </div>


  <footer class="footer bg-dark text-center w-100">
    <p class="text-muted">&copy; 2020 Awakelab.</p>
    <p class="text-muted">Grupo Full Stack Python</p>
  </footer>

  <!-- jQuery, Popper.js, Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
    </script>

  <script src="{% static 'js/login.js' %}"></script>
</body>

</html>

evaluacion_6.1/app1/templates/app1/lista_medicamentos.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<body>
    <h1>MEDICAMENTOS INDICADOS</h1>
    <a href="{% url 'app1:agregar_medicamento' %}"> Agregar</a>
    <br>
    <br>

    <table border="1px">
        <tr>
            <th>FECHA DE INDICACIÓN</th>
            <th>DOSIS</th>
            <th>MEDICAMENTO</th>
            <th>CÓDIGO</th>
            <th></th>
            <th></th>
        </tr>
        {% for elemento in medicamento %}
        <tr>
            <th>{{ elemento.fecha_indicacion }}</th>
            <th>{{ elemento.nombre }}</th>
            <th>{{ elemento.dosis }}</th>
            <th>{{ elemento.codigo }}</th>
            <th><a href="{% url 'app1:editar_medicamento' pk=elemento.codigo %}">Editar</a></th>
            <th><a href="{% url 'app1:eliminar_medicamento' pk=elemento.codigo %}">Eliminar</a></th>
        </tr>
        {% endfor %}
    </table>
</body>
{% endblock %}
</html>

evaluacion_6.1/app1/templates/app1/lista_paciente.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<body>
    <h1>LISTA PACIENTES</h1>
    <a href="{% url 'app1:crear' %}"> Agregar Paciente</a>
    <br>
    <table border="1px">
        <tr>
            <th>RUN</th>
            <th>NOMBRE</th>
            <th>APELLIDO</th>
            <th>FECHA DE NACIMIENTO</th>
            <th>EDAD</th>
            <th>DIRECCIÓN</th>
            <th>EMAIL</th>
            <th>TELÉFONO</th>
            <th>PATOLOGÍAS</th>
            <th></th>
            <th></th>
        </tr>
        {% for elemento in paciente %}
        <tr>
            <th>{{ elemento.run }}</th>
            <th>{{ elemento.nombre }}</th>
            <th>{{ elemento.apellido }}</th>
            <th>{{ elemento.fecha_nacimiento }}</th>
            <th>{{ elemento.edad }}</th>
            <th>{{ elemento.direccion }}</th>
            <th>{{ elemento.email }}</th>
            <th>{{ elemento.telefono }}</th>
            <th>{{ elemento.patologias }}</th>


            <th><a href="{% url 'app1:editar' pk=elemento.run %}">Editar</a></th>
            <th><a href="{% url 'app1:eliminar' pk=elemento.run %}">Eliminar</a></th>
        </tr>
        {% endfor %}
    </table>
</body>
{% endblock %}
</html>

evaluacion_6.1/app1/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <!-- Loading Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style-calendar.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style-nav.css' %}">
</head>

<body>
    <!--inicio navbar horizontal-->
    <nav class="navbar navbar-dark fixed-top bg-custom flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">SINARS</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse"
            data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a href="{% url 'app1:inicio' %}">Logout</a>
            </li>
        </ul>
    </nav>
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light pt-4 sidebar collapse">
        <div class="sidebar-sticky pt-3">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a href="{% url 'app1:lista' %}">
                        <h4>Home</h4>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'app1:examenes' %}">
                        
                        <h4>Exámenes</h4>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'app1:lista_medicamentos' %}">
                        
                        <h4>Medicamentos</h4>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'app1:cal' %}">
                        
                        <h4>Calendario</h4>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <!--fin navbar horizontal-->


    <div class="col-md-10 ml-auto">
        {% block content %}
        {% endblock %}  
    </div>        
    <br>
    <br>
    <footer class="text-center" style="height: 100px; background-color: black;">

        <p style="padding-top: 30px; text-decoration-color: white;">Full Stack Python 154-1 </p>

    </footer>


    <!-- jQuery, Popper.js, Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
        </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
        </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
        </script>
    <script src="{% static 'js/eventos_calendario.js' %}"></script>
    <script src="{% static 'js/logica_calendario.js' %}"></script>
</body>

</html>